"""Record modifications to Apache-2.0 licensed vendored plugins.

Apache-2.0 section 4(b) requires modified files to carry prominent notices
stating that they were changed. JSON manifests cannot carry comments, so the
notice goes in a MODIFICATIONS.md at the plugin root, listing every file this
repository's patch scripts touched and why.

Imported by patches/fix-*.sh. Only Apache-2.0 plugins get a file; for anything
else this is a no-op, because the obligation is specific to that licence.
"""

import os

_MARKER = '<!-- generated by patches/_apache_notice.py -- do not edit by hand -->'


def plugin_root(path, plugins_dir):
    """Return the top-level plugin directory containing `path`, or None."""
    rel = os.path.relpath(os.path.abspath(path), os.path.abspath(plugins_dir))
    if rel.startswith(os.pardir):
        return None
    top = rel.split(os.sep)[0]
    return os.path.join(plugins_dir, top) if top not in ('.', '') else None


def is_apache(plugin_dir):
    """True when the plugin ships an Apache-2.0 licence file."""
    try:
        names = os.listdir(plugin_dir)
    except OSError:
        return False
    for fn in names:
        if fn.upper().startswith(('LICENSE', 'LICENCE')):
            try:
                with open(os.path.join(plugin_dir, fn), encoding='utf-8', errors='ignore') as fh:
                    return 'APACHE LICENSE' in fh.read(400).upper()
            except OSError:
                return False
    return False


def _existing(plugin_dir):
    """Read back rows already recorded in a MODIFICATIONS.md we generated."""
    path = os.path.join(plugin_dir, 'MODIFICATIONS.md')
    rows = []
    try:
        with open(path, encoding='utf-8') as fh:
            text = fh.read()
    except OSError:
        return rows
    if _MARKER not in text:
        return rows  # hand-written file; leave its contents alone
    for line in text.splitlines():
        if line.startswith('| `') and line.endswith('|'):
            parts = [c.strip() for c in line.strip('|').split('|', 1)]
            if len(parts) == 2:
                rows.append((parts[0].strip('`'), parts[1]))
    return rows


def record(changes, plugins_dir):
    """Write MODIFICATIONS.md for each Apache-2.0 plugin in `changes`.

    changes: {absolute file path: reason string}

    Merges with any entries already recorded, because several patch scripts run
    in sequence and each sees only its own changes -- replacing the file would
    make the last script win and silently drop the others. Re-vendoring deletes
    the plugin directory, so the file starts empty again and cannot accumulate
    entries for files that are no longer modified.

    Returns the list of plugins documented.
    """
    by_plugin = {}
    for path, reason in changes.items():
        root = plugin_root(path, plugins_dir)
        if root and is_apache(root):
            by_plugin.setdefault(root, []).append(
                (os.path.relpath(path, root), reason))

    for root in list(by_plugin):
        by_plugin[root].extend(_existing(root))

    for root, entries in sorted(by_plugin.items()):
        name = os.path.basename(root)
        lines = [
            f'# Modifications to {name}',
            '',
            _MARKER,
            '',
            'This vendored copy differs from its upstream release. Recorded here to',
            'satisfy Apache License 2.0 section 4(b), which requires modified files to',
            'carry prominent notices stating that they were changed.',
            '',
            'The upstream LICENSE and any NOTICE are preserved unchanged. Rationale for',
            'each change is in `patches/README.md` at the repository root.',
            '',
            '| File | Change |',
            '|---|---|',
        ]
        for rel, reason in sorted(set(entries)):
            lines.append(f'| `{rel}` | {reason} |')
        lines.append('')

        with open(os.path.join(root, 'MODIFICATIONS.md'), 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(lines))

    return sorted(os.path.basename(r) for r in by_plugin)
