#!/usr/bin/env bash
# Export THIS MACHINE's Claude Code plugin state into plugins-claude-code.tsv.
# Run it on a machine that is working well, commit the result, then a new machine runs bootstrap-plugins.sh.
#
# Runs on bash 3.2 (the macOS default) - no mapfile, no associative arrays.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/plugins-claude-code.tsv"
DENY="$HERE/plugins-loai.tsv"
SRC="$HOME/.claude/plugins"

[ -d "$SRC" ] || { echo "Cannot find $SRC - is Claude Code installed on this machine?" >&2; exit 1; }

python3 - "$SRC" "$OUT" "$DENY" <<'PY'
import json, sys, datetime, os
src, out, deny_path = sys.argv[1], sys.argv[2], sys.argv[3]
km = json.load(open(os.path.join(src, 'known_marketplaces.json')))
ip = json.load(open(os.path.join(src, 'installed_plugins.json')))['plugins']

# The `pack` column is assigned by a person and cannot be derived from machine state.
# Re-read the old file to PRESERVE it - otherwise every export wipes the classification.
old_pack = {}
if os.path.exists(out):
    for line in open(out):
        if line.startswith('#'):
            continue
        f = line.rstrip('\n').split('\t')
        if len(f) >= 4 and f[0] == 'plugin' and f[3]:
            old_pack[f[1]] = f[3]

# Plugins rejected by the rubric - read so they are NOT pulled back into the install list.
# Without this file, every rejection decision is wiped on the next export.
# A row named `*` rejects the whole marketplace: its marketplace row is not written and all its plugins are dropped.
deny = {}
deny_mk = {}
if os.path.exists(deny_path):
    for line in open(deny_path):
        if line.startswith('#'):
            continue
        f = line.rstrip('\n').split('\t')
        if len(f) >= 3 and f[0]:
            if f[0] == '*':
                deny_mk[f[1]] = f[2]
            else:
                deny[f[0]] = f[2]

lines = [
    '# Generated by export-plugins.sh - do not edit by hand, EXCEPT the `pack` column.',
    '# Generated at: ' + datetime.datetime.now().isoformat(timespec='seconds'),
    '# Columns: kind<TAB>name<TAB>source<TAB>pack',
    '#',
    '# pack: core | code | web | vanphong | video | noidung | design | seo | ? (unclassified)',
    '# Applies to `plugin` rows only. Every marketplace is always added - a generous store, a tight enable list.',
    '# This column is assigned by hand and preserved by export across regenerations.',
    '#',
    '# Rejected entries live in plugins-loai.tsv and do not appear here. Scoring: scoring-layer-2.md',
]

local = []
skipped_mk = []
for name, info in sorted(km.items()):
    if name in deny_mk:
        skipped_mk.append((name, deny_mk[name]))
        continue
    s = info.get('source', {})
    kind = s.get('source')
    if kind == 'github':
        ref = s['repo']
    elif kind == 'git':
        ref = s['url']
    elif kind == 'directory':
        ref = s['path']
        local.append(name)
    else:
        ref = json.dumps(s, ensure_ascii=False)
    lines.append(f'marketplace\t{name}\t{ref}\t')

rows = sorted((k.partition('@')[2], k.partition('@')[0]) for k in ip)
new = []
blocked = []
for mk, n in rows:
    if mk in deny_mk:
        blocked.append((n, deny_mk[mk] + ' (ca marketplace)'))
        continue
    if n in deny:
        blocked.append((n, deny[n]))
        continue
    pack = old_pack.get(n, '?')
    if n not in old_pack:
        new.append(n)
    lines.append(f'plugin\t{n}\t{mk}\t{pack}')

open(out, 'w').write('\n'.join(lines) + '\n')
written = len(rows) - len(blocked)
print(f'Wrote {out}')
print(f'  {len(km) - len(skipped_mk)} marketplaces, {written} plugins (skipped {len(blocked)} rejected entries)')
if skipped_mk:
    print(f'  (i) {len(skipped_mk)} marketplaces rejected wholesale - not written to the TSV:')
    for n, rule in skipped_mk:
        print(f'    - {n}  [{rule}]')
    print('    This machine still has them registered. Remove with: claude plugin marketplace remove <name>')

kept = written - len(new)
print(f'  kept the previous pack for {kept} plugins')
if blocked:
    print(f'  (i) this machine has {len(blocked)} rejected plugins installed - not written to the TSV:')
    for n, rule in blocked:
        print(f'    - {n}  [{rule}]')
    print('    Remove with: claude plugin uninstall <name>   - to restore one, delete its row in plugins-loai.tsv')
if new:
    print(f'  ! {len(new)} NEW plugins have no pack yet (left as "?") and will not install unless --all:')
    print('    ' + ', '.join(new))
    print('    Assign a pack and commit, otherwise a new machine will skip them.')
if local:
    print('  ! marketplaces registered as a LOCAL DIRECTORY, which a new machine will not have: ' + ', '.join(local))
    print('    Re-register them by git URL before committing this file.')
PY
